// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_2tmWU21KvWouex4xfNJhgFIwwqadZKo',
    appId: '1:340541108319:web:fa8be19f239080d38aabea',
    messagingSenderId: '340541108319',
    projectId: 'taask-prod-b2dc6',
    authDomain: 'taask-prod-b2dc6.firebaseapp.com',
    storageBucket: 'taask-prod-b2dc6.appspot.com',
    measurementId: 'G-LXD8CWR3GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB30feFZ5anlofysyfJIeN66aK64OUhvMU',
    appId: '1:340541108319:android:7684c473254550558aabea',
    messagingSenderId: '340541108319',
    projectId: 'taask-prod-b2dc6',
    storageBucket: 'taask-prod-b2dc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCISU1wXc_5Tj0kOA76Ii-y5ujzPhVpG48',
    appId: '1:340541108319:ios:a9e5ff11654cf5d18aabea',
    messagingSenderId: '340541108319',
    projectId: 'taask-prod-b2dc6',
    storageBucket: 'taask-prod-b2dc6.appspot.com',
    iosBundleId: 'com.pestro.task',
  );
}
