// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_mock.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3M8uzH-B0zc_Vthyv6bMDD9ctvKmVPfQ',
    appId: '1:229333668561:web:e6e3730151dcaf6285abf0',
    messagingSenderId: '229333668561',
    projectId: 'taask-mock',
    authDomain: 'taask-mock.firebaseapp.com',
    storageBucket: 'taask-mock.appspot.com',
    measurementId: 'G-8J6MD6YMP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQbujr8z_1x7UffnNHe202tndEfrKfdIk',
    appId: '1:229333668561:android:bbd997bd43c4193c85abf0',
    messagingSenderId: '229333668561',
    projectId: 'taask-mock',
    storageBucket: 'taask-mock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIBAwEe_H4h5U-qDaaIF8bi2A-rp-8rck',
    appId: '1:229333668561:ios:d97350d1fb28978385abf0',
    messagingSenderId: '229333668561',
    projectId: 'taask-mock',
    storageBucket: 'taask-mock.appspot.com',
    iosBundleId: 'com.pestro.task.mock',
  );
}
