// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrkQq-6zE2egbQlIypxQYjoJiDrf1bAJ0',
    appId: '1:1054814973748:web:814454dcb0d7bc2e283f61',
    messagingSenderId: '1054814973748',
    projectId: 'taask-dev-11ac0',
    authDomain: 'taask-dev-11ac0.firebaseapp.com',
    storageBucket: 'taask-dev-11ac0.appspot.com',
    measurementId: 'G-YZPJ43KWGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1aGCdlBTzDpZCB1jGEcMJ-NUnYrl5Du8',
    appId: '1:1054814973748:android:db78042c2c03e3e6283f61',
    messagingSenderId: '1054814973748',
    projectId: 'taask-dev-11ac0',
    storageBucket: 'taask-dev-11ac0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ5idgXrjJcP839P5ZEusw3sCMBwMMjM8',
    appId: '1:1054814973748:ios:d33fcc4bfaa94a7c283f61',
    messagingSenderId: '1054814973748',
    projectId: 'taask-dev-11ac0',
    storageBucket: 'taask-dev-11ac0.appspot.com',
    iosBundleId: 'com.pestro.task.dev',
  );
}
